services:
  poll:
    build: ./poll
    init: true
    volumes:
      - ./poll:/poll
      - ./serviceAccountKey.json:/etc/gcp/serviceAccountKey.json
    working_dir: /poll
    command: python poll.py
    env_file: ./poll/.env
    restart: unless-stopped

  pubsub-smb-controller:
    build: ./pubsub-smb-controller
    init: true
    volumes:
      - ./pubsub-smb-controller/serviceAccountKey.json:/etc/gcp/serviceAccountKey.json
    env_file: ./pubsub-smb-controller/.env
    restart: unless-stopped
