services:
  mytvlog:
    build: .
    init: true
    ports:
      - 8001:8001
    volumes:
      - ./db:/app/db
    working_dir: /app
    command: docker-entrypoint.sh
    environment:
      TZ: Asia/Tokyo
      PORT: 8001
    env_file: .env
    restart: unless-stopped

  poll:
    image: python:3.13-slim
    init: true
    volumes:
      - ./poll:/poll
    working_dir: /poll
    command: python poll.py
    env_file: .env
    restart: unless-stopped
