services:
  mytvlog:
    build: .
    init: true
    ports:
      - 8001:8001
    volumes:
      - ./db:/app/db
      - ./serviceAccountKey.json:/etc/gcp/serviceAccountKey.json
    working_dir: /app
    environment:
      TZ: Asia/Tokyo
      PORT: 8001
    env_file: .env
    restart: unless-stopped

  poll:
    build: ./poll
    init: true
    volumes:
      - ./poll:/poll
    working_dir: /poll
    command: python poll.py
    env_file: .env
    restart: unless-stopped
