services:
  mytvlog:
    build: .
    ports:
      - 8001:80
    volumes:
      - ./api:/app/api
      - ./db:/app/db
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    working_dir: /app/api
    command: docker-entrypoint.sh
