services:
  mytvlog-dev:
    build:
      context: .
      target: dev
    init: true
    ports:
      - 8002:8001
    volumes:
      - .:/app
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ./db/tv.dev.db:/app/db/tv.db
      - ./serviceAccountKey.json:/etc/gcp/serviceAccountKey.json
    working_dir: /app
    command: docker-entrypoint.sh dev
    environment:
      TZ: Asia/Tokyo
      PORT: 8001
    env_file: .dev.env
    restart: no
